repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files

- repo: https://github.com/asottile/blacken-docs
  rev: v1.12.1
  hooks:
  - id: blacken-docs
    additional_dependencies: [black==22.6.0]

- repo: https://github.com/psf/black
  rev: 22.6.0
  hooks:
    - id: black
      args: [--config=pyproject.toml]

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      files: "\\.(py)$"
      args: [--settings-path=pyproject.toml]

- repo: local
  hooks:
  - id: pylint
    name: pylint
    entry: ./venv/bin/pylint
    language: system
    types: [python]
    args: [--ignore-patterns=venv]
